import { StructureType, Family, SubFamily } from "./types";

export const initialTypes: StructureType[] = [
    { id: "1", name: "Achat", color: "bg-blue-500" },
    { id: "2", name: "Fonctionnement", color: "bg-orange-500" },
    { id: "3", name: "Production", color: "bg-green-500" },
    { id: "4", name: "Vente", color: "bg-purple-500" },
];

export const initialFamilies: Family[] = [
    // ACHAT (Type 1)
    { id: "FA01", name: "Produits de Base", code: "FA01", typeId: "1" },
    { id: "FA02", name: "Fruits Secs / Epices", code: "FA02", typeId: "1" },
    { id: "FA03", name: "Produits Laitiers", code: "FA03", typeId: "1" },
    { id: "FA04", name: "Produits Fermiers", code: "FA04", typeId: "1" },
    { id: "FA05", name: "Viandes", code: "FA05", typeId: "1" },
    { id: "FA06", name: "Pâtisserie", code: "FA06", typeId: "1" },
    { id: "FA07", name: "Cuisine", code: "FA07", typeId: "1" },
    { id: "FA08", name: "Emballage", code: "FA08", typeId: "1" },
    { id: "FA09", name: "Energie et Fluides", code: "FA09", typeId: "1" },
    { id: "FA10", name: "Entretien et Hygiène", code: "FA10", typeId: "1" },
    { id: "FA11", name: "Matériel", code: "FA11", typeId: "1" },
    // FONCTIONNEMENT (Type 2)
    { id: "FF01", name: "Charges Externes", code: "FF01", typeId: "2" },
    { id: "FF02", name: "Personnel", code: "FF02", typeId: "2" },
    { id: "FF06", name: "Impôts et Taxes", code: "FF06", typeId: "2" },
    { id: "FF03", name: "Honoraires", code: "FF03", typeId: "2" },
    { id: "FF04", name: "Marketing & Communication", code: "FF04", typeId: "2" },
    { id: "FF05", name: "Maintenance et réparation Matériel", code: "FF05", typeId: "2" },
    // PRODUCTION (Type 3)
    { id: "FP01", name: "Boulangerie", code: "FP01", typeId: "3" },
    { id: "FP02", name: "Viennoiserie", code: "FP02", typeId: "3" },
    { id: "FP03", name: "Cakes & Cie", code: "FP03", typeId: "3" },
    { id: "FP04", name: "Base Commune", code: "FP04", typeId: "3" },
    { id: "FP05", name: "Pâtisserie", code: "FP05", typeId: "3" },
    { id: "FP06", name: "Cuisine", code: "FP06", typeId: "3" },
    { id: "FP07", name: "Fours Secs", code: "FP07", typeId: "3" },
    { id: "FP08", name: "Beldi", code: "FP08", typeId: "3" },
    { id: "FP09", name: "Gluten Diet", code: "FP09", typeId: "3" },
    // VENTE (Type 4)
    { id: "FV01", name: "Boulangerie", code: "FV01", typeId: "4" },
    { id: "FV02", name: "Viennoiseries", code: "FV02", typeId: "4" },
    { id: "FV03", name: "Pâtisserie", code: "FV03", typeId: "4" },
    { id: "FV04", name: "Gâteaux Secs", code: "FV04", typeId: "4" },
    { id: "FV05", name: "Salés", code: "FV05", typeId: "4" },
    { id: "FV06", name: "Confiserie", code: "FV06", typeId: "4" },
    { id: "FV07", name: "Gluten Diet", code: "FV07", typeId: "4" },
    { id: "FV08", name: "Supplément", code: "FV08", typeId: "4" },
];

export const initialSubFamilies: SubFamily[] = [
    // ACHAT
    { id: "FA011", name: "Farines", code: "FA011", familyId: "FA01" },
    { id: "FA012", name: "Sucres", code: "FA012", familyId: "FA01" },
    { id: "FA013", name: "Huiles", code: "FA013", familyId: "FA01" },
    { id: "FA014", name: "Base Divers", code: "FA014", familyId: "FA01" },
    { id: "FA021", name: "Fruits Secs", code: "FA021", familyId: "FA02" },
    { id: "FA022", name: "Epices", code: "FA022", familyId: "FA02" },
    { id: "FA023", name: "Divers", code: "FA023", familyId: "FA02" },
    { id: "FA031", name: "Lait", code: "FA031", familyId: "FA03" },
    { id: "FA032", name: "Crème Fraîche", code: "FA032", familyId: "FA03" },
    { id: "FA033", name: "Beurre", code: "FA033", familyId: "FA03" },
    { id: "FA034", name: "Fromage", code: "FA034", familyId: "FA03" },
    { id: "FA041", name: "Oeufs", code: "FA041", familyId: "FA04" },
    { id: "FA042", name: "Fruits", code: "FA042", familyId: "FA04" },
    { id: "FA043", name: "Légumes", code: "FA043", familyId: "FA04" },
    { id: "FA051", name: "Viandes Rouges", code: "FA051", familyId: "FA05" },
    { id: "FA052", name: "Volailles", code: "FA052", familyId: "FA05" },
    { id: "FA053", name: "Poisson", code: "FA053", familyId: "FA05" },
    { id: "FA054", name: "Asiatique", code: "FA054", familyId: "FA05" },
    { id: "FA061", name: "Chocolat", code: "FA061", familyId: "FA06" },
    { id: "FA062", name: "Produits Pâtissiers", code: "FA062", familyId: "FA06" },
    { id: "FA063", name: "Confiserie", code: "FA063", familyId: "FA06" },
    { id: "FA064", name: "Conserves Sucrés", code: "FA064", familyId: "FA06" },
    { id: "FA065", name: "Conserves Salés", code: "FA065", familyId: "FA06" },
    { id: "FA071", name: "Cuisine 1", code: "FA071", familyId: "FA07" },
    { id: "FA081", name: "Emballage Papier", code: "FA081", familyId: "FA08" },
    { id: "FA082", name: "Emballage Carton", code: "FA082", familyId: "FA08" },
    { id: "FA083", name: "Emballage Polystyrène", code: "FA083", familyId: "FA08" },
    { id: "FA084", name: "Consommable Emballage", code: "FA084", familyId: "FA08" },
    { id: "FA091", name: "Gasoil (Fours)", code: "FA091", familyId: "FA09" },
    { id: "FA092", name: "Gaz", code: "FA092", familyId: "FA09" },
    { id: "FA093", name: "Eau / Electricité", code: "FA093", familyId: "FA09" },
    { id: "FA094", name: "Téléphone", code: "FA094", familyId: "FA09" },
    { id: "FA095", name: "Gasoil (Voitures)", code: "FA095", familyId: "FA09" },
    { id: "FA096", name: "Fournitures Diverses", code: "FA096", familyId: "FA09" },
    { id: "FA101", name: "Produits de Ménage", code: "FA101", familyId: "FA10" },
    { id: "FA102", name: "Service Hygiène", code: "FA102", familyId: "FA10" },
    { id: "FA103", name: "Tenues de Personnel", code: "FA103", familyId: "FA10" },
    { id: "FA111", name: "Gros Matériel", code: "FA111", familyId: "FA11" },
    { id: "FA112", name: "Petit Matériel", code: "FA112", familyId: "FA11" },
    { id: "FA113", name: "Matériel Fours", code: "FA113", familyId: "FA11" },
    { id: "FA114", name: "Matériel Froid", code: "FA114", familyId: "FA11" },
    { id: "FA115", name: "Informatique / Bureautique", code: "FA115", familyId: "FA11" },
    { id: "FA116", name: "Matériel Electrique", code: "FA116", familyId: "FA11" },
    { id: "FA117", name: "Matériel Plomberie", code: "FA117", familyId: "FA11" },

    // FONCTIONNEMENT
    { id: "FF011", name: "Loyer", code: "FF011", familyId: "FF01" },
    { id: "FF012", name: "Assurance", code: "FF012", familyId: "FF01" },
    { id: "FF013", name: "Charges Ext Divers", code: "FF013", familyId: "FF01" },
    { id: "FF021", name: "Salaires", code: "FF021", familyId: "FF02" },
    { id: "FF022", name: "CNSS", code: "FF022", familyId: "FF02" },
    { id: "FF031", name: "Compta", code: "FF031", familyId: "FF03" },
    { id: "FF032", name: "Juridique", code: "FF032", familyId: "FF03" },
    { id: "FF033", name: "Honoraires Divers", code: "FF033", familyId: "FF03" },
    { id: "FF041", name: "Imprimerie", code: "FF041", familyId: "FF04" },
    { id: "FF042", name: "Publicité", code: "FF042", familyId: "FF04" },
    { id: "FF043", name: "Communication", code: "FF043", familyId: "FF04" },
    { id: "FF051", name: "Réparation Machines", code: "FF051", familyId: "FF05" },
    { id: "FF052", name: "Réparation Fours", code: "FF052", familyId: "FF05" },
    { id: "FF053", name: "Réparation Froid", code: "FF053", familyId: "FF05" },
    { id: "FF054", name: "Travaux Maçonnerie", code: "FF054", familyId: "FF05" },
    { id: "FF055", name: "Travaux Electricité", code: "FF055", familyId: "FF05" },
    { id: "FF056", name: "Travaux Plomberie", code: "FF056", familyId: "FF05" },
    { id: "FF057", name: "Maintenance Vitres", code: "FF057", familyId: "FF05" },
    { id: "FF061", name: "TVA", code: "FF061", familyId: "FF06" },
    { id: "FF062", name: "Frais de Timbre", code: "FF062", familyId: "FF06" },
    { id: "FF063", name: "IS", code: "FF063", familyId: "FF06" },
    { id: "FF064", name: "Taxe Pro", code: "FF064", familyId: "FF06" },
    { id: "FF065", name: "IR Salarial", code: "FF065", familyId: "FF06" },
    { id: "FF066", name: "IR Locatif", code: "FF066", familyId: "FF06" },
    { id: "FF067", name: "Taxe d'Enseigne", code: "FF067", familyId: "FF06" },

    // PRODUCTION
    { id: "FP011", name: "Pains Beldi", code: "FP011", familyId: "FP01" },
    { id: "FP012", name: "Pains Tradition", code: "FP012", familyId: "FP01" },
    { id: "FP013", name: "Pains de Mie", code: "FP013", familyId: "FP01" },
    { id: "FP021", name: "Croissants", code: "FP021", familyId: "FP02" },
    { id: "FP022", name: "Brioches", code: "FP022", familyId: "FP02" },
    { id: "FP023", name: "Crois. Beldi", code: "FP023", familyId: "FP02" },
    { id: "FP031", name: "Cakes & Cie", code: "FP031", familyId: "FP03" },
    { id: "FP032", name: "Amandes & Cie", code: "FP032", familyId: "FP03" },
    { id: "FP033", name: "Pommes & Cie", code: "FP033", familyId: "FP03" },
    { id: "FP034", name: "Vienn. Beldi", code: "FP034", familyId: "FP03" },
    { id: "FP041", name: "Base 1", code: "FP041", familyId: "FP04" },
    { id: "FP042", name: "Base 2", code: "FP042", familyId: "FP04" },
    { id: "FP043", name: "Base 3", code: "FP043", familyId: "FP04" },
    { id: "FP044", name: "Base 4", code: "FP044", familyId: "FP04" },
    { id: "FP051", name: "Biscuits", code: "FP051", familyId: "FP05" },
    { id: "FP052", name: "Crèmes & Mousses", code: "FP052", familyId: "FP05" },
    { id: "FP053", name: "Nougat & Craquant", code: "FP053", familyId: "FP05" },
    { id: "FP054", name: "Inserts", code: "FP054", familyId: "FP05" },
    { id: "FP055", name: "Gâteaux", code: "FP055", familyId: "FP05" },
    { id: "FP056", name: "Glaces", code: "FP056", familyId: "FP05" },
    { id: "FP061", name: "Cuisine 1", code: "FP061", familyId: "FP06" },
    { id: "FP062", name: "Cuisine 2", code: "FP062", familyId: "FP06" },
    { id: "FP063", name: "Cuisine 3", code: "FP063", familyId: "FP06" },
    { id: "FP064", name: "Cuisine 4", code: "FP064", familyId: "FP06" },
    { id: "FP071", name: "PF 1", code: "FP071", familyId: "FP07" },
    { id: "FP072", name: "PF 2", code: "FP072", familyId: "FP07" },
    { id: "FP073", name: "PF 3", code: "FP073", familyId: "FP07" },
    { id: "FP074", name: "PF 4", code: "FP074", familyId: "FP07" },
    { id: "FP081", name: "Beldi 1", code: "FP081", familyId: "FP08" },
    { id: "FP082", name: "Beldi 2", code: "FP082", familyId: "FP08" },
    { id: "FP083", name: "Beldi 3", code: "FP083", familyId: "FP08" },
    { id: "FP084", name: "Beldi 4", code: "FP084", familyId: "FP08" },
    { id: "FP091", name: "SG 1", code: "FP091", familyId: "FP09" },
    { id: "FP092", name: "SG 2", code: "FP092", familyId: "FP09" },
    { id: "FP093", name: "SG 3", code: "FP093", familyId: "FP09" },
    { id: "FP094", name: "SG 4", code: "FP094", familyId: "FP09" },

    // VENTE
    { id: "FV011", name: "Boulangerie", code: "FV011", familyId: "FV01" },
    { id: "FV021", name: "Croissanterie", code: "FV021", familyId: "FV02" },
    { id: "FV022", name: "Viennoiserie", code: "FV022", familyId: "FV02" },
    { id: "FV031", name: "Individuels", code: "FV031", familyId: "FV03" },
    { id: "FV032", name: "Entremets", code: "FV032", familyId: "FV03" },
    { id: "FV041", name: "Fours Secs", code: "FV041", familyId: "FV04" },
    { id: "FV042", name: "Beldi", code: "FV042", familyId: "FV04" },
    { id: "FV043", name: "Pré-Emballés", code: "FV043", familyId: "FV04" },
    { id: "FV051", name: "Salés", code: "FV051", familyId: "FV05" },
    { id: "FV061", name: "Confiserie", code: "FV061", familyId: "FV06" },
    { id: "FV071", name: "Pain SG", code: "FV071", familyId: "FV07" },
    { id: "FV072", name: "Gâteaux SG", code: "FV072", familyId: "FV07" },
    { id: "FV081", name: "Supp Traiteurs", code: "FV081", familyId: "FV08" },
    { id: "FV082", name: "Supp Caisse", code: "FV082", familyId: "FV08" },
];

export const initialUnits = ["Kg", "Litre", "Unité", "Carton", "Quintal", "Sac", "Palette", "Plateau", "Barquette", "Boite"];
